[project]
name = "new_flow"
version = "0.1.0"
description = "new_flow using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,tools]==1.7.2",
]

[project.scripts]
new_flow = "new_flow.main:run"
run_crew = "new_flow.main:run"
train = "new_flow.main:train"
replay = "new_flow.main:replay"
test = "new_flow.main:test"
run_with_trigger = "new_flow.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
